SELECT DISTINCT ?hoard ?mint WHERE {
 {
 ?hoard a nmo:Hoard ;
       dcterms:tableOfContents [ nmo:hasMint ?mint ]
 }
UNION
 { ?hoard a nmo:Hoard ;
    dcterms:tableOfContents [ nmo:hasTypeSeriesItem ?tsi ] .
  ?tsi nmo:hasMint ?mint .
 }
}

